  version: "3.9"
  services:
    app:
      build: .
      image: rubyapp
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: example
        POSTGRES_HOST: db
      volumes:
        - .:/app
      ports:
        - 3000:3000
    db:
      image: postgres:alpine3.15
      environment:
        POSTGRES_PASSWORD: example